version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: deepreviewer-backend:latest
    ports:
      - "5000:5000"

    # You can add volumes here if you want live reload:
    # volumes:
    #   - ./backend:/app

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    image: deepreviewer-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
