version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dti_reviewer-backend:latest
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    image: dti_reviewer-backend:latest
    entrypoint: []
    command: conda run --no-capture-output -n deepreviewer celery -A celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    image: dti_reviewer-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
    - VITE_API_BASE_URL=http://backend:5000
