# .github/workflows/build-docs.yml
name: Build & Deploy Docs

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: docs-env
          create-args: >-
            python=3
            sphinx
            sphinx_rtd_theme

      - name: Build HTML
        working-directory: docs
        run: |
          micromamba activate docs-env
          make html


      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
